name: hirami

networks:
  net:
    driver: bridge

services:
  postgres:
    image: postgres:18.1
    environment:
      POSTGRES_USER: hirami
      POSTGRES_PASSWORD: password
      POSTGRES_DB: hirami
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U hirami"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - net

  valkey:
    image: valkey/valkey-bundle:9.0
    ports:
      - "6379:6379"
    volumes:
      - valkey:/data
    networks:
      - net
    healthcheck:
      test: ["CMD", "valkey-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  mailpit:
    image: axllent/mailpit:v1.28
    restart: unless-stopped
    volumes:
      - mailpit:/data
    ports:
      - 8025:8025
      - 1025:1025
    networks:
      - net

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: hirami-server
    ports:
      - 3002:3002
    env_file:
      - ./server/.env
    depends_on:
      postgres:
        condition: service_healthy
      valkey:
        condition: service_healthy
    volumes:
      - ./server:/app
    command: go run .
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:3002/"]
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 10s
    networks:
      - net

  seed:
    build: ./server
    depends_on:
      server:
        condition: service_healthy
    command: go run ./cmd/seed/main.go
    restart: "no"
    environment:
      - HOST=server
      - PORT=3002
    networks:
      - net

  ml:
    build:
      context: ./ml
      dockerfile: Dockerfile
    container_name: hirami-ml
    ports:
      - "8000:8000"
    volumes:
      - ./ml:/app
      - /app/.venv
    command: uv run uvicorn main:app --host 0.0.0.0
    networks:
      - net

volumes:
  postgres:
  valkey:
  mailpit:
