name: hirami

services:
  postgres:
    image: postgres:latest
    container_name: hirami-pg
    environment:
      POSTGRES_USER: hirami
      POSTGRES_PASSWORD: password
      POSTGRES_DB: hirami
    ports:
      - "5432:5432"
    volumes:
      - hirami-pg:/var/lib/postgresql/data

  valkey:
    image: valkey/valkey-bundle:latest
    container_name: hirami-valkey
    ports:
      - "6379:6379"
    volumes:
      - hirami-valkey:/data

  mailpit:
    image: axllent/mailpit
    container_name: hirami-mailpit
    restart: unless-stopped
    volumes:
      - hirami-mailpit:/data
    ports:
      - 8025:8025
      - 1025:1025

  server:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: hirami-server
    ports:
      - 3002:3002
    env_file:
      - .env
    depends_on:
      - postgres
      - valkey
    volumes:
      - .:/app
    command: go run .
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:3002/"]
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 10s

  seed:
    build: .
    depends_on:
      server:
        condition: service_healthy
    command: go run ./cmd/seed/main.go
    restart: "no"
    environment:
      - HOST=server
      - PORT=3002

  ml:
    build:
      context: ../ml
      dockerfile: Dockerfile
    container_name: hirami-ml
    ports:
      - "8000:8000"
    volumes:
      - ../ml:/app
      - /app/.venv
    command: uv run uvicorn main:app --host 0.0.0.0

volumes:
  hirami-pg:
  hirami-valkey:
  hirami-mailpit:
